import { notFound } from "next/navigation";
import { z } from "zod";
import { withTenant } from "@/db/tenant";
import { settlementInstructionText } from "@/domain/money";
import { getDb, requireMember } from "@/lib/server";
import { settlementDetails } from "@/modules/money/recipients";
import * as repo from "@/modules/money/repo";
import { markSettledAction } from "../../actions";
import { Flash, fmtDate, money } from "../../ui";
import styles from "./print.module.css";

export const metadata = { title: "Settlement instruction" };
export const dynamic = "force-dynamic";

/** Printable instruction: the paying party's copy. Use the browser's print (or save as PDF). */
export default async function Instruction({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; ok?: string }> }) {
  const { id } = await params;
  const { error, ok } = await searchParams;
  if (!z.string().uuid().safeParse(id).success) notFound();
  const { member, tenant } = await requireMember();
  const data = await withTenant(await getDb(), tenant, async (q) => {
    const i = (await repo.listInstructions(q, { id }))[0];
    if (!i) return null;
    const line = (await repo.getLine(q, i.payoutLineId))!;
    // Payee bank details only for people who can pay; assistants see the instruction without them.
    const details =
      line.amountMinor <= 0 ? null
      : member.role === "assistant" ? ((await repo.getRecipient(q, line.recipientId))?.hasSettlementDetails ? "(On file; visible to owners, advisors and admins.)" : null)
      : await settlementDetails(q, tenant.workspaceId, line.recipientId);
    return { i, details };
  });
  if (!data) notFound();
  const { i, details } = data;
  const text = settlementInstructionText({
    payer: { name: i.payerName, email: i.payerEmail },
    payee: { name: i.payeeName, email: i.payeeEmail },
    amountMinor: i.amountMinor,
    currency: i.currency,
    reference: i.reference,
    purpose: i.purpose,
    payeeDetails: details,
  });

  return (
    <main className={styles.sheet}>
      <Flash error={error} ok={ok} />
      <p className="small muted">Settlement instruction · issued {fmtDate(i.issuedAt)} · generated by the agency&apos;s booking system</p>
      <h1>
        Send {money(i.amountMinor, i.currency)} to {i.payeeName}
      </h1>
      <p className="lede">
        Reference <b>{i.reference}</b> · status <span className={`chip ${i.status === "settled" ? "ok" : "warn"}`}>{i.status}</span>
        {i.settledAt ? ` on ${fmtDate(i.settledAt)}` : ""}
      </p>
      <pre className={styles.text}>{text}</pre>
      {member.role === "owner" && i.status === "issued" && (
        <form action={markSettledAction} className={`actions ${styles.noPrint}`}>
          <input type="hidden" name="instructionId" value={i.id} />
          <input type="hidden" name="back" value={`/money/instructions/${i.id}`} />
          <button className="btn primary">Mark settled</button>
        </form>
      )}
    </main>
  );
}
